### ISSUE TITLE
react-day-picker styling issues with shad/ui 

### ISSUE THREAD

**Issue by LinnJS** [Maliksidk19/shadcn-datetime-picker#1]
## Description
I am trying to get this datetime picker setup to use at my works component library.

We are using shad/ui currently and these patterns looked like a great fit for what we are looking for. 

I copied the code from the v2 component and added it to storybook. I was using the same version react-day-picker as you were and it seems like the buttonVariant styles are messing up some of the styles with the days across the top. 

Also having issues with the Month and Year select not being styled as well.

Here is what it looks like on both versions of react-day-picker

react-day-picker@8.10.1

<img width="1053" alt="image" src="https://github.com/user-attachments/assets/b9a66ce8-3c96-4a4a-ab25-4953caba5ce9">

react-day-picker@9.0.6

<img width="1064" alt="image" src="https://github.com/user-attachments/assets/29d69c40-eb1e-4086-8f3f-8ca689dc7b0e">

It looks pretty broken on both versions arguably the newer version is a bit worse. Do you know what the issue could be? We have all the tailwind plugins installed when removing the button variants it looks better but unstyled.

Thank you for taking the time to post this repo and add it to the shad/ui awesome list.

**Comment by Maliksidk19** [comment]
the calender.tsx component is changed then the original calender.tsx component from shadcn ui, use the one in the repository not from the shadcn

**Comment by LinnJS** [comment]
Roger that thank you, will try that out.

**Comment by LinnJS** [comment]
> the calender.tsx component is changed then the original calender.tsx component from shadcn ui, use the one in the repository not from the shadcn

This was the missing piece thank you for taking the time to respond!
