### ISSUE TITLE
On Popover open the current month is opened insetad of the selected date's month

### ISSUE THREAD

**Issue by Giddu** [Maliksidk19/shadcn-datetime-picker#2]
![Screen Recording 2024-10-18 142933](https://github.com/user-attachments/assets/67d48e65-44a0-4d4c-afff-c7bc6b9a0971)

**Comment by Giddu** [comment]
I have provided a fix in my PR for the same #3

**Comment by Maliksidk19** [comment]
Thanks buddy ❤️
